Error: /vyatta-cpu-history-client: GetState failure: Traceback
Issue: VRVDR-50559

The CPU History service is needed by system configuration.
Updated service to use bus activation so that it is started
on first request.

(cherry picked from commit bdd508d0e5bb6cac355c5368a42510d11b6e542c)